server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: resources/, static/, public/, \ META-INF/resources/, resources/, classpath:static/, public/, classpath:META-INF/resources/, \file:///tmp/webapps/